TOP_STOCKS = [
    {"symbol": "AAPL", "name": "Apple Inc.", "sector": "Technology"},
    {"symbol": "MSFT", "name": "Microsoft Corporation", "sector": "Technology"},
    {"symbol": "GOOGL", "name": "Alphabet Inc.", "sector": "Technology"},
    {"symbol": "AMZN", "name": "Amazon.com Inc.", "sector": "Consumer Cyclical"},
    {"symbol": "NVDA", "name": "NVIDIA Corporation", "sector": "Technology"},
    {"symbol": "META", "name": "Meta Platforms Inc.", "sector": "Technology"},
    {"symbol": "TSLA", "name": "Tesla Inc.", "sector": "Consumer Cyclical"},
    {"symbol": "BRK.B", "name": "Berkshire Hathaway Inc.", "sector": "Financial"},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co.", "sector": "Financial"},
    {"symbol": "V", "name": "Visa Inc.", "sector": "Financial"},
    {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Healthcare"},
    {"symbol": "WMT", "name": "Walmart Inc.", "sector": "Consumer Defensive"},
    {"symbol": "PG", "name": "Procter & Gamble Co.", "sector": "Consumer Defensive"},
    {"symbol": "MA", "name": "Mastercard Inc.", "sector": "Financial"},
    {"symbol": "UNH", "name": "UnitedHealth Group Inc.", "sector": "Healthcare"},
    {"symbol": "HD", "name": "Home Depot Inc.", "sector": "Consumer Cyclical"},
    {"symbol": "DIS", "name": "Walt Disney Co.", "sector": "Communication"},
    {"symbol": "BAC", "name": "Bank of America Corp.", "sector": "Financial"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "sector": "Technology"},
    {"symbol": "CRM", "name": "Salesforce Inc.", "sector": "Technology"},
    {"symbol": "NFLX", "name": "Netflix Inc.", "sector": "Communication"},
    {"symbol": "CMCSA", "name": "Comcast Corporation", "sector": "Communication"},
    {"symbol": "XOM", "name": "Exxon Mobil Corporation", "sector": "Energy"},
    {"symbol": "PFE", "name": "Pfizer Inc.", "sector": "Healthcare"},
    {"symbol": "KO", "name": "Coca-Cola Co.", "sector": "Consumer Defensive"},
    {"symbol": "PEP", "name": "PepsiCo Inc.", "sector": "Consumer Defensive"},
    {"symbol": "COST","name": "Costco Wholesale Corp.","sector": "Consumer Defensive",},
    {"symbol": "ABBV", "name": "AbbVie Inc.", "sector": "Healthcare"},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific", "sector": "Healthcare"},
    {"symbol": "CSCO", "name": "Cisco Systems Inc.", "sector": "Technology"},
    {"symbol": "ABT", "name": "Abbott Laboratories", "sector": "Healthcare"},
    {"symbol": "MRK", "name": "Merck & Co. Inc.", "sector": "Healthcare"},
    {"symbol": "CVX", "name": "Chevron Corporation", "sector": "Energy"},
    {"symbol": "ACN", "name": "Accenture plc", "sector": "Technology"},
    {"symbol": "AVGO", "name": "Broadcom Inc.", "sector": "Technology"},
    {"symbol": "NKE", "name": "Nike Inc.", "sector": "Consumer Cyclical"},
    {"symbol": "LLY", "name": "Eli Lilly and Co.", "sector": "Healthcare"},
    {"symbol": "ORCL", "name": "Oracle Corporation", "sector": "Technology"},
    {"symbol": "DHR", "name": "Danaher Corporation", "sector": "Healthcare"},
    {"symbol": "MCD", "name": "McDonald's Corporation", "sector": "Consumer Cyclical"},
    {"symbol": "QCOM", "name": "Qualcomm Inc.", "sector": "Technology"},
    {"symbol": "TXN", "name": "Texas Instruments Inc.", "sector": "Technology"},
    {"symbol": "NEE", "name": "NextEra Energy Inc.", "sector": "Utilities"},
    {"symbol": "UPS", "name": "United Parcel Service Inc.", "sector": "Industrials"},
    {"symbol": "AMD", "name": "Advanced Micro Devices Inc.", "sector": "Technology"},
    {"symbol": "SPGI", "name": "S&P Global Inc.", "sector": "Financial"},
    {"symbol": "INTU", "name": "Intuit Inc.", "sector": "Technology"},
    {"symbol": "AMGN", "name": "Amgen Inc.", "sector": "Healthcare"},
    {"symbol": "GS", "name": "Goldman Sachs Group Inc.", "sector": "Financial"},
    {"symbol": "ISRG", "name": "Intuitive Surgical Inc.", "sector": "Healthcare"},
]
